project:
  name: vertex-pinecone-mcp
  region: us-central1
vertex:
  endpoint_name: gcp-crewai
  model_name: vertex-pinecone-mcp-model
openai:
  embedding_model: text-embedding-3-small
  embedding_dimensions: 1024
  generation_model: gpt-4.1-mini
autogen:
  model: gpt-4.1-mini
  temperature: 0
pinecone:
  index: news-demo
  namespace: news
  memory_namespace: memory
  host: https://news-demo-4fe9eo0.svc.aped-4627-b74a.pinecone.io
